### ISSUE TITLE
Improvement: Allow pfind command to work for surnames

### ISSUE THREAD

**Issue by teclu** [CS2103AUG2017-T13-B1/main#132]
Command pfind only looks at the first few characters of the name string. e.g. **pfind b** fill give you Bernice Yu, but not Roy Balakrishnan.

**Comment by RSJunior37** [comment]
The current implementation is intentional and I have no intention of modifying this. Real-time searchbox is effective since you don't need type a lot to get what you want but if you includes surnames and alike (including long separated names) then you'll be getting a lot of irrelevant hits and forced to type more to narrow down the search
